// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtjprftW0b8zdJgalWdYXnJJJyDsdZNS4',
    appId: '1:764644211759:web:12e7f0b30d2d814fa5dada',
    messagingSenderId: '764644211759',
    projectId: 'fir-lumuzik',
    authDomain: 'fir-lumuzik.firebaseapp.com',
    storageBucket: 'fir-lumuzik.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ-7nFflJdD8AXEC9f6x_zrzfw78BJvHc',
    appId: '1:764644211759:android:dc6c6d4d738d9c90a5dada',
    messagingSenderId: '764644211759',
    projectId: 'fir-lumuzik',
    storageBucket: 'fir-lumuzik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6PKVt1OQe7lqScJud7aC3lv3v9QNpwNI',
    appId: '1:764644211759:ios:1aae3716554e7e46a5dada',
    messagingSenderId: '764644211759',
    projectId: 'fir-lumuzik',
    storageBucket: 'fir-lumuzik.firebasestorage.app',
    iosBundleId: 'com.example.lumuzik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6PKVt1OQe7lqScJud7aC3lv3v9QNpwNI',
    appId: '1:764644211759:ios:1aae3716554e7e46a5dada',
    messagingSenderId: '764644211759',
    projectId: 'fir-lumuzik',
    storageBucket: 'fir-lumuzik.firebasestorage.app',
    iosBundleId: 'com.example.lumuzik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtjprftW0b8zdJgalWdYXnJJJyDsdZNS4',
    appId: '1:764644211759:web:253ae022f83bdfe7a5dada',
    messagingSenderId: '764644211759',
    projectId: 'fir-lumuzik',
    authDomain: 'fir-lumuzik.firebaseapp.com',
    storageBucket: 'fir-lumuzik.firebasestorage.app',
  );
}
